# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Utilizando box eunati/apache2
  config.vm.box = "eunati/apache2"

  # Mapeando a porta 80 (HTTP) da máquina virtual guest para a porta 8080 
  # do host apenas no IP 127.0.0.1 (acesso local)
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Sincronizando a pasta html para o caminho /var/www/html/hello na máquina
  # virtual guest
  config.vm.synced_folder "./html", "/var/www/html/hello"
end
